import type { User, Agency, Property, AgencyProperty, Favorite, Purchase, AgencyClient, TopBuyer, TopRankedProperty, TopAgencySales } from './types'

export const users: User[] = [
  { id: 1, username: 'manuel', email: 'manuel@argentina.gob', profileType: 'BUYER' },
  { id: 2, username: 'claudia', email: 'claudia@mail.com', profileType: 'BUYER' },
  { id: 3, username: 'karina', email: 'karina@argentina.gob', profileType: 'ADMIN' },
  { id: 4, username: 'jorge', email: 'jorge@mail.com', profileType: 'BUYER' },
  { id: 5, username: 'patricia', email: 'patricia@mail.com', profileType: 'BUYER' },
  { id: 6, username: 'roberto', email: 'roberto@mail.com', profileType: 'BUYER' },
  { id: 7, username: 'ana', email: 'ana@mail.com', profileType: 'BUYER' },
  { id: 8, username: 'diego', email: 'diego@mail.com', profileType: 'BUYER' },
  { id: 9, username: 'laura', email: 'laura@mail.com', profileType: 'BUYER' },
  { id: 10, username: 'martin', email: 'martin@mail.com', profileType: 'BUYER' },
  { id: 11, username: 'sofia', email: 'sofia@mail.com', profileType: 'BUYER' },
  { id: 12, username: 'lucas', email: 'lucas@mail.com', profileType: 'BUYER' },
  { id: 13, username: 'valentina', email: 'valentina@mail.com', profileType: 'BUYER' },
  { id: 14, username: 'nicolas', email: 'nicolas@mail.com', profileType: 'BUYER' },
  { id: 15, username: 'camila', email: 'camila@mail.com', profileType: 'BUYER' },
  { id: 16, username: 'admin123', email: 'admin@cth.com', profileType: 'ADMIN' },
]

export const agencies: Agency[] = [
  { id: 1, username: 'ritondo_propiedades', email: 'ritondo@propiedades.com' },
  { id: 2, username: 'nordelta_propiedades', email: 'contacto@nordeltapropiedades.com' },
  { id: 3, username: 'puerto_madero_brokers', email: 'info@pmbrokers.com' },
  { id: 4, username: 'sur_inversiones', email: 'ventas@surinversiones.com' },
  { id: 5, username: 'agro_bienes_raices', email: 'campo@agrobienesraices.com' },
  { id: 6, username: 'patagonia_bienes', email: 'sur@patagoniabienes.com' },
];

export const properties: Property[] = [
  {
    id: 1,
    propertyType: 'APARTMENT',
    price: 230000,
    address: 'Miró 548',
    city: 'Ciudad de Buenos Aires',
    province: 'Ciudad de Buenos Aires',
    areaSq: 230,
    rooms: 3,
    description: 'semipiso hermoso cuatro ambientes al frente con cochera y baulera',
    available: true,
    agencyId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 2,
    propertyType: 'HOUSE',
    price: 200000,
    address: 'Indio Cua 380',
    city: 'Exaltación de la Cruz',
    province: 'Buenos Aires',
    areaSq: 400,
    rooms: 6,
    description: 'Oportunidad en Indio Cuá Golf Club: Casa con lote de 400 m2 en Exaltación de la Cruz',
    available: true,
    agencyId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 3,
    propertyType: 'HOUSE',
    price: 890000,
    address: 'Barrio La Isla, Lote 45',
    city: 'Tigre',
    province: 'Buenos Aires',
    areaSq: 550,
    rooms: 7,
    description: 'Espectacular casa al lago en el barrio más exclusivo de Nordelta. Terminaciones de categoría.',
    available: true,
    agencyId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 4,
    propertyType: 'APARTMENT',
    price: 520000,
    address: 'Juana Manso 1100',
    city: 'Ciudad de Buenos Aires',
    province: 'Ciudad de Buenos Aires',
    areaSq: 120,
    rooms: 3,
    description: 'Exclusivo departamento en piso alto en Puerto Madero. Vista al dique, amenities premium.',
    available: true,
    agencyId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 5,
    propertyType: 'APARTMENT',
    price: 720000,
    address: 'Posadas 1500',
    city: 'Ciudad de Buenos Aires',
    province: 'Ciudad de Buenos Aires',
    areaSq: 180,
    rooms: 4,
    description: 'Semipiso de gran categoría en pleno Recoleta. Palier privado, seguridad 24hs.',
    available: true,
    agencyId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 6,
    propertyType: 'HOUSE',
    price: 430000,
    address: 'Estancia Villa Maria, Lote 8',
    city: 'Ezeiza',
    province: 'Buenos Aires',
    areaSq: 320,
    rooms: 5,
    description: 'Casa estilo toscano en el exclusivo club de campo Estancia Villa María. Gran parque.',
    available: true,
    agencyId: 4,
    imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 7,
    propertyType: 'APARTMENT',
    price: 950000,
    address: 'Av. Alvear 1800',
    city: 'Ciudad de Buenos Aires',
    province: 'Ciudad de Buenos Aires',
    areaSq: 260,
    rooms: 5,
    description: 'Piso barra señorial sobre Av. Alvear. Estilo francés, techos altos, detalles de boiserie.',
    available: true,
    agencyId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 8,
    propertyType: 'HOUSE',
    price: 580000,
    address: 'Barrio Castores, Lote 112',
    city: 'Tigre',
    province: 'Buenos Aires',
    areaSq: 380,
    rooms: 5,
    description: 'Hermosa propiedad desarrollada en dos plantas en Los Castores. Piscina y costa de lago.',
    available: true,
    agencyId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9,
    propertyType: 'APARTMENT',
    price: 210000,
    address: 'Juncal 2300',
    city: 'Ciudad de Buenos Aires',
    province: 'Ciudad de Buenos Aires',
    areaSq: 85,
    rooms: 3,
    description: 'Departamento de 3 ambientes reciclado a nuevo en Barrio Norte. Muy luminoso.',
    available: false,
    agencyId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 10,
    propertyType: 'HOUSE',
    price: 115000,
    address: 'Aymonino 300',
    city: 'Rio Gallegos',
    province: 'Santa Cruz',
    areaSq: 160,
    rooms: 4,
    description: 'Casa familiar sólida en zona residencial de Río Gallegos. Entrada para vehículos.',
    available: true,
    agencyId: 6,
    imageUrl: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 11,
    propertyType: 'HOUSE',
    price: 480000,
    address: 'Av. Bustillo Km 4.5',
    city: 'San Carlos de Bariloche',
    province: 'Río Negro',
    areaSq: 290,
    rooms: 5,
    description: 'Propiedad con costa de lago Nahuel Huapi. Vistas panorámicas inigualables.',
    available: true,
    agencyId: 6,
    imageUrl: 'https://images.unsplash.com/photo-1449034446853-66c86144b0ad?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 12,
    propertyType: 'APARTMENT',
    price: 340000,
    address: 'Ugarteche 3000',
    city: 'Ciudad de Buenos Aires',
    province: 'Ciudad de Buenos Aires',
    areaSq: 110,
    rooms: 3,
    description: 'Excelente departamento en la exclusiva zona de Palermo Nuevo. Balcón corrido.',
    available: true,
    agencyId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 13,
    propertyType: 'HOUSE',
    price: 390000,
    address: 'Club de Campo San Diego, Lote 24',
    city: 'Moreno',
    province: 'Buenos Aires',
    areaSq: 420,
    rooms: 6,
    description: 'Casa de categoría en San Diego Country Club. Amplias comodidades and suite principal.',
    available: true,
    agencyId: 4,
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 14,
    propertyType: 'APARTMENT',
    price: 280000,
    address: 'Av. Coronel Diaz 2100',
    city: 'Ciudad de Buenos Aires',
    province: 'Ciudad de Buenos Aires',
    areaSq: 95,
    rooms: 3,
    description: 'Departamento frente al shopping Alto Palermo. Excelente ubicación y conectividad.',
    available: true,
    agencyId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 15,
    propertyType: 'APARTMENT',
    price: 850000,
    address: 'Martín Coronado 3200',
    city: 'Ciudad de Buenos Aires',
    province: 'Ciudad de Buenos Aires',
    areaSq: 210,
    rooms: 4,
    description: 'Piso exclusivo en torre de categoría en Palermo Chico. Vista despejada al parque.',
    available: false,
    agencyId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 16,
    propertyType: 'HOUSE',
    price: 550000,
    address: 'Barrio Highland Park, Los Alamos 45',
    city: 'Pilar',
    province: 'Buenos Aires',
    areaSq: 450,
    rooms: 6,
    description: 'Casa señorial refaccionada en Highland Park. Excelente arboleda y piscina.',
    available: true,
    agencyId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 17,
    propertyType: 'APARTMENT',
    price: 165000,
    address: 'Boulevard Marítimo 2300',
    city: 'Mar del Plata',
    province: 'Buenos Aires',
    areaSq: 70,
    rooms: 3,
    description: 'Departamento con vista plena al mar en edificio céntrico de Mar del Plata.',
    available: true,
    agencyId: 4,
    imageUrl: 'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 18,
    propertyType: 'HOUSE',
    price: 720000,
    address: 'Ruta 40 Km 2200, Estancia El Desafío',
    city: 'San Martín de los Andes',
    province: 'Neuquén',
    areaSq: 310,
    rooms: 5,
    description: 'Moderna casa de montaña en barrio cerrado con cancha de polo y golf.',
    available: true,
    agencyId: 6,
    imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
  }
];

export const agencyProperties: AgencyProperty[] = [
  // --- PROPIEDADES MULTI-AGENCIA ---
  {
    id: 1,
    propertyId: 1, // Miró 548
    address: 'Miró 548',
    city: 'Ciudad de Buenos Aires',
    propertyType: 'APARTMENT',
    listedPrice: 230000,
    listedDate: '2025-01-01',
    available: true,
    agencyId: 1,
    agencyName: 'ritondo_propiedades',
  },
  {
    id: 2,
    propertyId: 1, // Miró 548
    address: 'Miró 548',
    city: 'Ciudad de Buenos Aires',
    propertyType: 'APARTMENT',
    listedPrice: 245000,
    listedDate: '2025-02-15',
    available: true,
    agencyId: 3,
    agencyName: 'puerto_madero_brokers',
  },
  {
    id: 3,
    propertyId: 2, // Indio Cua 380
    address: 'Indio Cua 380',
    city: 'Exaltación de la Cruz',
    propertyType: 'HOUSE',
    listedPrice: 200000,
    listedDate: '2025-01-15',
    available: false,
    agencyId: 1,
    agencyName: 'ritondo_propiedades',
  },
  {
    id: 4,
    propertyId: 3, // Barrio La Isla, Lote 45
    address: 'Barrio La Isla, Lote 45',
    city: 'Tigre',
    propertyType: 'HOUSE',
    listedPrice: 890000,
    listedDate: '2026-01-02',
    available: true,
    agencyId: 1,
    agencyName: 'ritondo_propiedades',
  },
  {
    id: 5,
    propertyId: 3, 
    address: 'Barrio La Isla, Lote 45',
    city: 'Tigre',
    propertyType: 'HOUSE',
    listedPrice: 900000,
    listedDate: '2025-02-02',
    available: true,
    agencyId: 2,
    agencyName: 'nordelta_propiedades',
  },
  {
    id: 6,
    propertyId: 7, // Av. Alvear 1800
    address: 'Av. Alvear 1800',
    city: 'Ciudad de Buenos Aires',
    propertyType: 'APARTMENT',
    listedPrice: 950000,
    listedDate: '2025-03-05',
    available: true,
    agencyId: 3,
    agencyName: 'puerto_madero_brokers',
  },
  {
    id: 7,
    propertyId: 7, // Av. Alvear 1800
    address: 'Av. Alvear 1800',
    city: 'Ciudad de Buenos Aires',
    propertyType: 'APARTMENT',
    listedPrice: 920000,
    listedDate: '2025-04-01',
    available: true,
    agencyId: 1,
    agencyName: 'ritondo_propiedades',
  },
  {
    id: 8,
    propertyId: 13, // San Diego, Lote 24
    address: 'Club de Campo San Diego, Lote 24',
    city: 'Moreno',
    propertyType: 'HOUSE',
    listedPrice: 390000,
    listedDate: '2025-04-20',
    available: true,
    agencyId: 4,
    agencyName: 'sur_inversiones',
  },
  {
    id: 9,
    propertyId: 13, // San Diego, Lote 24
    address: 'Club de Campo San Diego, Lote 24',
    city: 'Moreno',
    propertyType: 'HOUSE',
    listedPrice: 410000,
    listedDate: '2025-05-02',
    available: true,
    agencyId: 5,
    agencyName: 'agro_bienes_raices',
  },

  // --- CARTERA DE RITONDO PROPIEDADES ---
  {
    id: 10,
    propertyId: 9, // Juncal 2300
    address: 'Juncal 2300',
    city: 'Ciudad de Buenos Aires',
    propertyType: 'APARTMENT',
    listedPrice: 210000,
    listedDate: '2025-03-22',
    available: false,
    agencyId: 1,
    agencyName: 'ritondo_propiedades',
  },
  {
    id: 11,
    propertyId: 12, // Ugarteche 3000
    address: 'Ugarteche 3000',
    city: 'Ciudad de Buenos Aires',
    propertyType: 'APARTMENT',
    listedPrice: 340000,
    listedDate: '2025-04-15',
    available: true,
    agencyId: 1,
    agencyName: 'ritondo_propiedades',
  },
  {
    id: 12,
    propertyId: 14, // Av. Coronel Diaz 2100
    address: 'Av. Coronel Diaz 2100',
    city: 'Ciudad de Buenos Aires',
    propertyType: 'APARTMENT',
    listedPrice: 280000,
    listedDate: '2025-05-14',
    available: true,
    agencyId: 1,
    agencyName: 'ritondo_propiedades',
  },

  // --- RESTO DEL MERCADO ---
  {
    id: 13,
    propertyId: 4, // Juana Manso 1100
    address: 'Juana Manso 1100',
    city: 'Ciudad de Buenos Aires',
    propertyType: 'APARTMENT',
    listedPrice: 520000,
    listedDate: '2025-02-11',
    available: true,
    agencyId: 3,
    agencyName: 'puerto_madero_brokers',
  },
  {
    id: 14,
    propertyId: 5, // Posadas 1500
    address: 'Posadas 1500',
    city: 'Ciudad de Buenos Aires',
    propertyType: 'APARTMENT',
    listedPrice: 720000,
    listedDate: '2025-02-25',
    available: true,
    agencyId: 3,
    agencyName: 'puerto_madero_brokers',
  },
  {
    id: 15,
    propertyId: 6, // Estancia Villa Maria, Lote 8
    address: 'Estancia Villa Maria, Lote 8',
    city: 'Ezeiza',
    propertyType: 'HOUSE',
    listedPrice: 430000,
    listedDate: '2025-03-01',
    available: true,
    agencyId: 4,
    agencyName: 'sur_inversiones',
  },
  {
    id: 16,
    propertyId: 8, // Barrio Castores, Lote 112
    address: 'Barrio Castores, Lote 112',
    city: 'Tigre',
    propertyType: 'HOUSE',
    listedPrice: 580000,
    listedDate: '2025-03-18',
    available: true,
    agencyId: 2,
    agencyName: 'nordelta_propiedades',
  },
  {
    id: 17,
    propertyId: 10, // Aymonino 300
    address: 'Aymonino 300',
    city: 'Rio Gallegos',
    propertyType: 'HOUSE',
    listedPrice: 115000,
    listedDate: '2025-04-02',
    available: true,
    agencyId: 6,
    agencyName: 'patagonia_bienes',
  },
  {
    id: 18,
    propertyId: 11, // Av. Bustillo Km 4.5
    address: 'Av. Bustillo Km 4.5',
    city: 'San Carlos de Bariloche',
    propertyType: 'HOUSE',
    listedPrice: 480000,
    listedDate: '2025-04-09',
    available: true,
    agencyId: 6,
    agencyName: 'patagonia_bienes',
  },
  {
    id: 19,
    propertyId: 15, // Martín Coronado 3200
    address: 'Martín Coronado 3200',
    city: 'Ciudad de Buenos Aires',
    propertyType: 'APARTMENT',
    listedPrice: 850000,
    listedDate: '2025-05-28',
    available: false,
    agencyId: 3,
    agencyName: 'puerto_madero_brokers',
  },
  {
    id: 20,
    propertyId: 16, // Barrio Highland Park, Los Alamos 45
    address: 'Barrio Highland Park, Los Alamos 45',
    city: 'Pilar',
    propertyType: 'HOUSE',
    listedPrice: 550000,
    listedDate: '2025-06-02',
    available: true,
    agencyId: 2,
    agencyName: 'nordelta_propiedades',
  },
  {
    id: 21,
    propertyId: 17, // Boulevard Marítimo 2300
    address: 'Boulevard Marítimo 2300',
    city: 'Mar del Plata',
    propertyType: 'APARTMENT',
    listedPrice: 165000,
    listedDate: '2025-06-10',
    available: true,
    agencyId: 4,
    agencyName: 'sur_inversiones',
  },
  {
    id: 22,
    propertyId: 18, // Ruta 40 Km 2200, Estancia El Desafío
    address: 'Ruta 40 Km 2200, Estancia El Desafío',
    city: 'San Martín de los Andes',
    propertyType: 'HOUSE',
    listedPrice: 720000,
    listedDate: '2025-06-15',
    available: true,
    agencyId: 6,
    agencyName: 'patagonia_bienes',
  }
];

export const favorites: Favorite[] = [
  {
    id: 1,
    agencyPropertyId: 1,
    propertyAddress: 'Miró 548',
    city: 'Ciudad de Buenos Aires',
    agencyName: 'ritondo_propiedades',
    score: 5,
    comment: 'Faltan renovaciones, buscar financiamiento',
    savedPrice: 340000,
    savedDate: '2025-04-01',
  },
]

export const purchases: Purchase[] = [
  {
    id: 1,
    agencyId: 1,
    propertyAddress: 'Indio Cua 380',
    agencyName: 'ritondo_propiedades',
    purchasePrice: 150000,
    purchaseDate: '2024-03-15',
  },
]

export const agencyClients: AgencyClient[] = [
  { agencyId: 1, userId: 1, username: 'manuel', email: 'manuel@argentina.gob' },
]

export const topBuyers: TopBuyer[] = [
  { userId: 1, username: 'manuel', purchases: 3 },
  { userId: 2, username: 'claudia', purchases: 1 },
]

export const topRankedProperties: TopRankedProperty[] = [
  { propertyId: 1, address: 'Miró 548', averageScore: 8.5, ratings: 4 },
  { propertyId: 2, address: 'Indio Cua 380', averageScore: 7.2, ratings: 2 },
]

export const topAgenciesSales: TopAgencySales[] = [
  { agencyId: 1, username: 'ritondo_propiedades', sales: 5 },
]
